###############################################
# 全局设置
###############################################

# 8位数字，生成Authenticator的秘钥
# 并不是Authenticator，而是生成Authenticator的秘钥
# 必填
key:
# HTTP请求的服务器地址端口
# 注意需要走IPTV专用网络才能访问通。
# 必填
serverHost: 182.138.3.142:8082
# 自定义HTTP请求头
headers:
  Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
  User-Agent: "Mozilla/5.0 (X11; Linux x86_64; Fhbw2.0) AppleWebKit"
  Accept-Language: "zh-CN,en-US;q=0.8"
  X-Requested-With: "com.fiberhome.iptv"
# 频道的过滤规则，仅支持正则表达式
# 获取频道列表时，匹配该规则的频道会被过滤掉
chExcludeRule: "^.+?(画中画|单音轨|-体验)$"
# 频道分组规则
# 依照顺序识别频道分组，且仅支持正则表达式
chGroupRules:
  - name: 央视
    rules:
      - "^(CCTV|中央).+?$"
  - name: 卫视
    rules:
      - "^[^(热门)].+?卫视.*?$"
  - name: 国际
    rules:
      - "^(CGTN|凤凰).+?$"
  - name: 地方
    rules:
      - "^(SCTV|CDTV).+?$" # 四川地方频道
      - "^(浙江|杭州|民生|钱江|教科影视|好易购|西湖|青少体育).+?$" # 浙江地方频道
      - "^(湖北|武汉).+?$" # 湖北地方频道
  - name: 专区
    rules:
      - ".+?专区$"
# 频道台标匹配规则
# 依照顺序识别频道台标，且仅支持正则表达式
# 根据匹配转换后的名称（name），从./logos目录中查询对应的台标图片
# 若频道名称不匹配以下任意台标规则，则将根据频道本身的名称来查询对应的台标图片
logos:
  - rule: "^CCTV-?(.+?)(标清|高清|超清)?$" # 匹配规则
    # 使用$G1, $G2等，可自动替换为正则表达式的对应分组。
    name: "CCTV$G1" # 转换后的台标名称
  - rule: "^([^(热门)].+?)卫视(标清|高清|超清)?$"
    name: "$G1卫视"
  - rule: "^CDTV-?(.+?)(标清|高清|超清)?$"
    name: "CDTV$G1"
  - rule: "^SCTV-?(.+?)(标清|高清|超清)?$"
    name: "SCTV$G1"
  - rule: "^CETV-?(.+?)(标清|高清|超清)?$"
    name: "CETV$G1"

###############################################
# hw平台相关设置
hwctc:
  # "interfaceName"和"ip"至少填写一个，若都填写则优先使用"interfaceName"指定的接口对应的IPv4地址
  # 生成Authenticator所需的网络接口名称，可通过配置自动获取指定接口的IPv4地址。用于获取软路由上某接口被自动分配的IPTV线路的IP地址。
  interfaceName:
  # 生成Authenticator所需的客户端的ip，可任意配置
  ip:

  # 认证接口ValidAuthenticationHWCTC.jsp的相关参数
  # 必填
  userID:
  lang:
  netUserID:
  # 必填
  stbType:
  # 必填
  stbVersion:
  conntype:
  # 必填
  stbID:
  templateName:
  areaId:
  userGroupId:
  productPackageId:
  # 必填
  mac:
  userField:
  softwareVersion:
  isSmartStb:
  vip:

  # 获取EPG信息的API
  # 目前支持3种："liveplay_30"，"gdhdpublic"或"vsp"
  # 未设置时，将自动进行尝试。
  channelProgramAPI: